### ISSUE TITLE
Raise exceptions on responses from slack

### ISSUE THREAD

**Issue by dblock** [aki017/slack-ruby-gem#17]
Slack responses and errors are standardized, why don't we raise a specific exception when something fails and do it "the ruby way" instead of returning a hash on failure that needs to be parsed every single time?

Happy to contribute that. For now I just monkey patch as such:

``` ruby
module Slack
  module Request
    private

    alias_method :_request, :request

    def request(method, path, options)
      response = _request(method, path, options)
      if response.is_a?(Hash)
        unless response['ok']
          fail response['error']
        end
      end
      response
    end
  end
end
```

**Comment by dblock** [comment]
@aki017 What do you think about this? I am happy to contribute a PR.

**Comment by aki017** [comment]
@dblock very nice idea!

**Comment by dblock** [comment]
@aki017 PR in https://github.com/aki017/slack-ruby-gem/pull/27.
