### ISSUE TITLE
Document RTM getting started in README

### ISSUE THREAD

**Issue by dblock** [aki017/slack-ruby-gem#18]
The getting started gets you only that far. Extend the README, maybe with http://code.dblock.org/2015/04/28/slack-bot-real-time-messaging-api-integration-tutorial.html.

**Comment by aki017** [comment]
:laughing:

**Comment by dblock** [comment]
I feel like a link to my tutorial is not the best way to do this and as much as I like the traffic and the attention I think all of that belongs in the README, I ported the content into the README in https://github.com/aki017/slack-ruby-gem/pull/40.
