### ISSUE TITLE
Worn with real time messaging?

### ISSUE THREAD

**Issue by angelacode** [aki017/slack-ruby-gem#30]
Does this gem support the real time messaging API ?

**Comment by dblock** [comment]
@angelacode Yes it does. See http://code.dblock.org/2015/04/28/slack-bot-real-time-messaging-api-integration-tutorial.html for a getting started.

**Comment by angelacode** [comment]
awesome, thanks that's cool....

**Comment by ajmarquez** [comment]
Hi! does it supports the reactions_added and reactions_removed events?

**Comment by dblock** [comment]
It doesn't, but https://github.com/dblock/slack-ruby-client does.

**Comment by ajmarquez** [comment]
Sorry but I only see 4 methods https://github.com/dblock/slack-ruby-client/tree/master/lib/slack/real_time/api , how may I access reactions_added? Thanks in advance :)

**Comment by dblock** [comment]
@ajmarquez reactions are a web api, not an rtm api or am I missing something? Open an issue in that project if you need help.

**Comment by ajmarquez** [comment]
@dblock  In deed, its also a Real Time API method https://api.slack.com/rtm it notifies when a reaction is added or removed. 

I'll do that! :)
