### ISSUE TITLE
How to pass a new line for multiline?

### ISSUE THREAD

**Issue by angelacode** [aki017/slack-ruby-gem#32]
Based on the documentation I just need to pass a \n to get a newline. 

However when I do it it doesn't generate a new line but just displays te \n. 

I tried using the % character as well and same thing: no new line.

**Comment by dblock** [comment]
Had no trouble doing this with [slack-ruby-client](https://github.com/dblock/slack-ruby-client). Happy to help there.

```ruby
client.message channel: channel, text: "Line1\nLine2."
```
