### ISSUE TITLE
Suport for RTM API

### ISSUE THREAD

**Issue by sciurus** [aki017/slack-ruby-gem#4]
Are you planning to add support for slack's new [real time messaging API](https://api.slack.com/rtm)?

**Comment by mackwic** [comment]
@sciurus FYI I wrote a gem that supports the slack rtm api. [It's here](https://github.com/mackwic/slack-rtmapi). I already use it in one of my project so it's working. I will be glad to take feedback or document how to do specific integrations.

**Comment by mackwic** [comment]
OK, I didn't saw that @aki017 already added the RTM support in the gem. Thanks for that !
My implementation doesn't depend on EventMachine, though. That was a requirement for my side.

**Comment by aki017** [comment]
commited 91ed4c7ad43823c32e11c5f9061bc5c4484291cb
and released v1.0.0! :grinning:

**Comment by dblock** [comment]
Looks like now slack-ruby-gem is a hybrid of RTM and Web API client, it receives messages via RTM but sends via Web API.
