### ISSUE TITLE
Updated runtime dependencies

### ISSUE THREAD

**Issue by tsutsui** [aki017/slack-ruby-gem#50]
The latest version of faye-websocket is 0.10.6 and faraday_middleware has newer 0.11.0.1, but slack.gemspec explicitly specify older versions in runtime dependencies.
It looks slack-api works with these latest versions, at least with https://github.com/Na0ki/mikutter_slack .
Is it possible to update slack.gemspec to accept these newer gems?

**Comment by aki017** [comment]
Updated dev branch, Release in a few days with more testing.
https://github.com/aki017/slack-ruby-gem/commit/626dc1f5a45baee099c85a44be49138b712a4875
Thanks
