### ISSUE TITLE
Real time quits when an image is recieved

### ISSUE THREAD

**Issue by TheSimkin** [aki017/slack-ruby-gem#56]
This one is kind of weird.  When an image link is recieved by the bot the rtm just quits no errors or anything.

If I restart it, it quits again and eventually floods itself off of slack ( or if i send a new message so the last message sent isn't an image any more )

**Comment by TheSimkin** [comment]
i think i might have been causing this issue myself by 'returning' from inside of the real-time block!

I can no longer reproduce this bug after rubocop pointed out this issuee.

**Comment by aki017** [comment]
👍
