### ISSUE TITLE
register the gem in the slack community integrations ?

### ISSUE THREAD

**Issue by mackwic** [aki017/slack-ruby-gem#6]
Hi !
slack-ruby-gem is not listed in [the community integrations of slack](https://api.slack.com/community)

Maybe opening an issue to them to add the gem to the list ?

Regards,

**Comment by aki017** [comment]
I requested now! :wink:
Maybe listed in few days.

**Comment by aki017** [comment]
Done :dancers: 
> slack-ruby-gem - A Ruby wrapper for the Slack API

**Comment by mackwic** [comment]
:+1:

--  
Thomas Wickham
thomas@wickham.epimeros.org

De: Akiteru Maeda <notifications@github.com>
Répondre: aki017/slack-ruby-gem <reply@reply.github.com>>
Date: 13 janvier 2015 at 03:48:50
À: aki017/slack-ruby-gem <slack-ruby-gem@noreply.github.com>>
Cc: Thomas Wickham <thomas@wickham.epimeros.org>>
Sujet:  Re: [slack-ruby-gem] register the gem in the slack community integrations ? (#6)  

Closed #6.
