### ISSUE TITLE
File.upload method doesn't work, correct?

### ISSUE THREAD

**Issue by pkpp1233** [aki017/slack-ruby-gem#7]
It seems to pseudo-work if you just send the *content* parameter, but is it possible to send through the *file* parameter? It doesn't seem to work with the normal way of creating a payload with Faraday:

    my_file = Faraday::UploadIO.new("logo.svg", 'image/svg')
    Slack.files_upload({
        channel: "#general",
        file: my_file
    })

I'll just do the call directly with Farday, but still wanted to bring up.

**Comment by aki017** [comment]
fixed :grinning:
